In [1]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
matriz = np.array(matriz)

In [11]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[1]

2

In [15]:
arr[0] + arr[5]

7

In [17]:
matriz[0,2]

3

In [19]:
arr[0:3]

array([1, 2, 3])

In [20]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [21]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [22]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[::3]

array([1, 4, 7])

In [25]:
arr[-3:]

array([7, 8, 9])

In [26]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])