In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr = np.array([1,2,3,4], dtype = 'float64')

In [6]:
arr.dtype

dtype('float64')

In [7]:
arr

array([1., 2., 3., 4.])

In [ ]:
arr = np.array([1,2,3,4])

In [9]:
arr = arr.astype(np.float64)

In [10]:
arr

array([1., 2., 3., 4.])

In [5]:
arr = np.array([0,1,2,3,4])

In [7]:
arr = arr.astype(np.bool_)

In [8]:
arr

array([False,  True,  True,  True,  True])

In [21]:
arr = np.array([0,1,2,3,4])

In [22]:
arr = arr.astype(np.string_)

In [23]:
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [24]:
arr = np.array(['0','1','2','3','4'])

In [25]:
arr = arr.astype(np.int8)

In [26]:
arr

array([0, 1, 2, 3, 4], dtype=int8)