In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)

In [3]:
matriz = arr.reshape(2, 5)

In [4]:
arr

array([14,  7,  5,  7, 15, 12, 11,  5, 13,  1])

In [5]:
arr.max()

15

In [6]:
matriz

array([[14,  7,  5,  7, 15],
       [12, 11,  5, 13,  1]])

In [7]:
matriz.max()

15

In [8]:
matriz.max(1)

array([15, 13])

In [9]:
matriz.max(0)

array([14, 11,  5, 13, 15])

In [10]:
arr.argmax()

4

In [11]:
matriz.argmax(0)

array([0, 1, 0, 1, 0])

In [12]:
arr.min()

1

In [13]:
matriz.min()

1

In [15]:
matriz.argmin(1)

array([2, 4])

In [16]:
arr.ptp()

14

In [17]:
matriz.ptp(0)

array([ 2,  4,  0,  6, 14])

In [18]:
np.percentile(arr, 50)

9.0

In [19]:
arr.sort()

In [20]:
arr

array([ 1,  5,  5,  7,  7, 11, 12, 13, 14, 15])

In [21]:
np.median(arr)

9.0

In [22]:
np.median(matriz, 1)

array([ 5., 13.])

In [23]:
np.std(arr)

4.404543109109048

In [24]:
np.var(arr)

19.4

In [25]:
np.mean(arr)

9.0

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [28]:
a

array([[1, 2],
       [3, 4]])

In [30]:
np.concatenate((a, b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [31]:
a.ndim

2

In [32]:
b.ndim

1

In [36]:
b_ = np.expand_dims(b, axis = 0)

In [38]:
b_

array([[5, 6]])

In [37]:
np.concatenate((a, b_), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.concatenate((a, b_.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])