In [2]:
import numpy as np

In [3]:
lista = [1, 2]

In [4]:
lista

[1, 2]

In [5]:
lista * 2

[1, 2, 1, 2]

In [6]:
arr = np.arange(0, 10)

In [7]:
arr2 = arr.copy()

Operaciones

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
11/arr

/tmp/ipykernel_512014/2505916109.py:1: RuntimeWarning: divide by zero encountered in divide
  11/arr


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

In [12]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr*arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
matriz = arr.reshape(2,5)

In [17]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz2 = matriz.copy()

In [19]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [22]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [25]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [26]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])